name: Metrics
on:
  schedule: [{ cron: "0 0/24 * * *" }]
  workflow_dispatch:
  push: { branches: ["main", "master"] }
 
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions: { contents: write }
    steps:
      - name: Generate profile card
        uses: lowlighter/metrics@latest
        with:
         
          token: ${{ secrets.METRICS_TOKEN }}   
          user:  Johnnyallen07        

          # classic template"
          base: header, activity, community, repositories, metadata
          plugin_lines: yes                             
    

          # — languages plugin —
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_ignored: >-
            html, css

          # try to add some achievements"

          # plugin_achievements: yes
          # plugin_achievements_display: detailed

          # Achievement system crashed

          # detect the total line of code
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_analysis_timeout: 15

          # add org
          repositories_affiliations: owner, organization_member

          # recently used
          # plugin_languages_sections: recently-used