name: Metrics
on:
  schedule: [{ cron: "0 0/24 * * *" }]
  workflow_dispatch:
  push: { branches: ["main", "master"] }
 
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions: { contents: write }
    steps:
      - name: Generate profile card
        uses: lowlighter/metrics@latest
        with:
         
          token: ${{ secrets.METRICS_TOKEN }}   
          user:  Johnnyallen07        

          # classic template"
          base: header, repositories
          plugin_lines: yes                             
    

          # — languages plugin —
          plugin_languages: yes
          plugin_languages_limit: 16
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot